---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxyserver
    author: legal
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxyserver
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxyserver
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            requests:
              memory: "128Mi"
              cpu: "253m"
            limits:
              memory: "256Mi"
              cpu: "500m"
...

