---
version: '3.8'
services:
 voting-app:
  image: dockersamples/examplevotingapp_vote
  ports:
   - 5050:80
  deploy:
   replicas: 2

 myredis:
  image: redis
  ports:
   - 6379:6379

 worker:
  image: dockersamples/examplevotingapp_worker

 mydb:
  image: postgres
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: lgl
   POSTGRES_USER: legaluser
   POSTGRES_DB: legaldb

 result-app:
  image: dockersamples/examplevotingapp_result
  ports:
   - 6060:8080
  deploy:
   replicas: 2

...
